name: Manual Test & Build & Deploy

on:
  workflow_dispatch:
  # Any branch
  
env:
  AZURE_WEBAPP_NAME: "Weather-api-12345"

jobs:
  run-domain-tests:
    runs-on: ubuntu-latest
    environment:
      name: 'manual-run-all-tests'
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore Weather.Domain.Tests/Weather.Domain.Tests.csproj
      - name: Build tests
        run: dotnet build Weather.Domain.Tests/Weather.Domain.Tests.csproj --configuration Release --no-restore
      - name: Run tests
        run: dotnet test Weather.Domain.Tests/Weather.Domain.Tests.csproj --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=test-results-web.xml"
      # - name: Test Report
      #   uses: phoenix-actions/test-reporting@v8
      #   id: domain-test-reporter
      #   if: success() || failure()
      #   with:
      #     name: test-report-domain
      #     path: Weather.Domain.Tests/TestResults/test-results-web.xml
      #     reporter: dotnet-trx
      - name: Upload tests results
        uses: actions/upload-artifact@v3
        with:
          name: test-results-web
          path: '**/test-results-web.xml'
          if-no-files-found: error
  
  run-powershell-tests:
    runs-on: ubuntu-latest
    environment:
      name: 'manual-run-all-tests'
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore Weather.Cmdlets.Tests/Weather.Cmdlets.Tests.csproj
      - name: Build tests
        run: dotnet build Weather.Cmdlets.Tests/Weather.Cmdlets.Tests.csproj --configuration Release --no-restore
      - name: Run tests
        run: dotnet test Weather.Cmdlets.Tests/Weather.Cmdlets.Tests.csproj --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=test-results-powershell.xml"
      # - name: Test Report
      #   uses: phoenix-actions/test-reporting@v8
      #   id: powershell-test-reporter
      #   if: success() || failure()
      #   with:
      #     name: test-report-powershell
      #     path: Weather.Cmdlets.Tests/TestResults/test-results-powershell.xml
      #     reporter: dotnet-trx
      - name: Upload tests results
        uses: actions/upload-artifact@v3
        with:
          name: test-results-powershell
          path: '**/test-results-powershell.xml'
          if-no-files-found: error
  
  run-shared-tests:
    runs-on: ubuntu-latest
    environment:
      name: 'manual-run-all-tests'
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore Weather.Shared.Tests/Weather.Shared.Tests.csproj
      - name: Build tests
        run: dotnet build Weather.Shared.Tests/Weather.Shared.Tests.csproj --configuration Release --no-restore
      - name: Run tests
        run: dotnet test Weather.Shared.Tests/Weather.Shared.Tests.csproj --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=test-results-shared.xml"
      # - name: Test Report
      #   uses: phoenix-actions/test-reporting@v8
      #   id: shared-test-reporter
      #   if: success() || failure()
      #   with:
      #     name: test-report-shared
      #     path: Weather.Shared.Tests/TestResults/test-results-shared.xml
      #     reporter: dotnet-trx
      - name: Upload tests results
        uses: actions/upload-artifact@v3
        with:
          name: test-results-shared
          path: '**/test-results-shared.xml'
          if-no-files-found: error

  run-pester-tests:
    runs-on: ubuntu-latest
    environment:
      name: 'manual-run-all-tests'
    steps:
      - uses: actions/checkout@v3
      - name: Invoke-Pester
        shell: pwsh
        run: |
          # install and import Pester
          if (-not (Get-Module -ListAvailable -Name Pester | Where-Object {$_.Version -eq "5.2.2"})) {
              Install-Module -Name Pester -RequiredVersion 5.2.2 -Scope CurrentUser -Force
          }
      
          if (-not (Get-Module -Name Pester)) {
              Import-Module Pester -RequiredVersion 5.2.2 -Force -Global -PassThru
          }
          
          # Execute all tests
          $testScriptsPath = "Weather.Cmdlets.Tests/Pester"
      
          # Create the test results file
          $testResultsFile = "Weather.Cmdlets.Tests/TEST-Results.Pester.xml"
      
          if (Test-Path $testResultsFile) {
              Remove-Item -Path $testResultsFile
          }
      
          $pesterConfiguration = [PesterConfiguration]@{
              Run = @{
                  Path = $testScriptsPath;
              };
              TestResult = @{
                  Enabled = $true;
                  OutputPath = $testResultsFile;
                  OutputFormat = 'NUnitXML';
              };
              Filter = @{
                  ExcludeTag = 'Excluded';
              }
          }

          Invoke-Pester -Configuration $pesterConfiguration
      - name: Upload tests results
        uses: actions/upload-artifact@v3
        with:
          name: test-results-pester
          path: '**/TEST-Results.Pester.xml'
          if-no-files-found: error

# Web
  build-web:
    needs: [run-domain-tests, run-powershell-tests, run-shared-tests]
    runs-on: ubuntu-latest
    environment:
      name: 'manual-build-web'
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore Weather/Weather.csproj
      - name: Build
        run: dotnet build Weather/Weather.csproj --configuration Release --no-restore
      - name: Publish
        run: dotnet publish Weather/Weather.csproj --configuration Release --output "Weather/publish_artifacts" --no-build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: weather-api-artifacts
          path: "Weather/publish_artifacts/**"
          if-no-files-found: error

  deploy-dev:
    needs: build-web
    runs-on: ubuntu-latest
    environment:
      name: 'dev'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: weather-api-artifacts
          path: weather-api-artifacts
      - name: Deploy to Azure
        id: deploy-to-azure
        uses: azure/webapps-deploy@v2
        with:
          # just use the same azure web-app as a 'dev'.
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: weather-api-artifacts

  deploy-prod:
    needs: build-web
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: weather-api-artifacts
          path: weather-api-artifacts
      - name: Deploy to Azure
        id: deploy-to-azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: weather-api-artifacts

# Nuget package
  prerelease-shared-nuget-package:
    needs: [run-shared-tests]
    runs-on: ubuntu-latest
    environment:
      name: 'nuget-prerelease'
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Create the prerelease package
        shell: pwsh
        run: |
          $version = [System.DateTime]::Now.ToString("yyyy.MM.dd.HHmm") + "-prerelease"
          dotnet pack Weather.Shared/Weather.Shared.csproj -p:PackageVersion=$version --configuration Release --output "Weather.Shared/package_artifacts"
      - name: Upload to nuget
        run: dotnet nuget push "Weather.Shared/package_artifacts/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

  release-shared-nuget-package:
    needs: [run-shared-tests]
    runs-on: ubuntu-latest
    environment:
      name: 'nuget-release'
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Create the release package
        shell: pwsh
        run: |
          $version = [System.DateTime]::Now.ToString("yyyy.MM.dd.HHmm")
          dotnet pack Weather.Shared/Weather.Shared.csproj -p:PackageVersion=$version --configuration Release --output "Weather.Shared/package_artifacts"
      - name: Upload to nuget
        run: dotnet nuget push "Weather.Shared/package_artifacts/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

  release-myget-package:
    needs: [run-pester-tests]
    runs-on: ubuntu-latest
    environment:
      name: 'myget-release'
    steps:
      - uses: actions/checkout@v3
      - name: Build cmdlets
        run: dotnet build Weather.Cmdlets/Weather.Cmdlets.csproj --configuration Release --no-restore
      - name: Upload to myget
        shell: pwsh
        run: |
          Import-Module PowerShellGet
          $FeedName = "ci-cd-basics-packages"
          $PSGalleryPublishUri = 'https://www.myget.org/F/$FeedName/api/v2/package'
          $PSGallerySourceUri = 'https://www.myget.org/F/$FeedName/api/v2'
          $APIKey = "5d8d8afa-e399-4cb4-965e-edab5944268e"

          # Publish the module the the SkyKick MyGet PowerShell feed
          $ModulePath = "Weather.Cmdlets/Release/net6.0"
          Register-PSRepository -Name $FeedName -SourceLocation $PSGallerySourceUri -PublishLocation $PSGalleryPublishUri
          Publish-Module -Path $(ModulePath) -NuGetApiKey $APIKey -Repository $FeedName -Verbose
